kind: pipeline
name: default

workspace:
  base: /go
  path: src/github.com/pavanbelagatti/mysa/main

steps:
- name: test
  image: golang
  commands:
  - go mod init
  - go get
  - go test
 
 settings:
   repo:pavansa/mysa
   username:
     from_secret: docker_username
   password:
     from_secret: docker_password
   tags:
     - latest
