kind: pipeline
name: default

workspace:
  base: /go
  path: src/github.com/pavanbelagatti/mysa/main

steps:
- name: test
  image: golang
  commands:
  - go mod init
  - go get
  - go test

- name: docker  
  image: plugins/docker
  settings:
    # registry: docker.io
    repo: dockertodaynow/test
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags: 
      - latest