kind: pipeline
name: default


- name: docker  
  image: plugins/docker
  settings:
    # registry: docker.io
    repo: dockertodaynow/test
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags: 
      - latest