kind: pipeline
type: docker
name: default

workspace:
  base: /go
  path: src/github.com/pavanbelagatti/mysa/main

steps:
- name: docker
  image: plugins/golang
  commands:
  - go mod init
  - go get
  - go test

settings:
    # registry: docker.io
    repo: pavansa/bangaloretour
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags: 
      - latest
